import frappe
from frappe import _

# DIED table mappings
# These are mappings from ERPNext values to LODAS values according to the DIED tables
DIED_MAPPINGS = {
    # DIED 4003: Gender
    "gender": {
        'Male': '1',
        'Female': '2',
        'Other': '0',
        '': '0'  # Default value
    },
    
    # DIED 4004: Marital Status
    "marital_status": {
    "Single":   "0",
    "Unmarried": "0",      # synonym, if used
    "Divorced": "0",
    "Widowed":  "0",
    "Separated": "0",
    "Married":  "1"
    },
    
    # DIED 4012: Employment Type (example - adjust with actual codes from manual)
    "custom_arbeitsverhältnis": {
        "Unbefristet": "0",       # Unbefristet
        "Befristet": "1",      # Befristet (temporary with end date)
        "Zweckbefristet": "2" # Zweckbefristet (ends when a goal is achieved)
    },
    
    # DIED 4005: Nationality (simplified example - would need full country codes from manual)
    'custom_land' : {
    "Germany": "000",
    "Albania": "121",
    "Bosnia and Herzegovina": "122",
    "Andorra": "123",
    "Belgium": "124",
    "Bulgaria": "125",
    "Denmark": "126",
    "Estonia": "127",
    "Finland": "128",
    "France": "129",
    "Croatia": "130",
    "Slovenia": "131",
    "Serbia and Montenegro": "132",
    "Serbia (incl. Kosovo)": "133",
    "Greece": "134",
    "Ireland": "135",
    "Iceland": "136",
    "Italy": "137",
    "Yugoslavia": "138",
    "Latvia": "139",
    "Montenegro": "140",
    "Liechtenstein": "141",
    "Lithuania": "142",
    "Luxembourg": "143",
    "North Macedonia": "144",
    "Malta": "145",
    "Moldova": "146",
    "Monaco": "147",
    "Netherlands": "148",
    "Norway": "149",
    "Kosovo": "150",
    "Austria": "151",
    "Poland": "152",
    "Portugal": "153",
    "Romania": "154",
    "Slovakia": "155",
    "San Marino": "156",
    "Sweden": "157",
    "Switzerland": "158",
    "Russia": "160",
    "Spain": "161",
    "Turkey": "163",
    "Czech Republic": "164",
    "Hungary": "165",
    "Ukraine": "166",
    "Vatican City": "167",
    "United Kingdom": "168",
    "Belarus": "169",
    "Serbia": "170",
    "Cyprus": "181",
    "Gibraltar": "195",
    "Other Europe": "199",
    "Algeria": "221",
    "Angola": "223",
    "Eritrea": "224",
    "Ethiopia": "225",
    "Lesotho": "226",
    "Botswana": "227",
    "Benin": "229",
    "Djibouti": "230",
    "Côte d'Ivoire": "231",
    "Nigeria": "232",
    "Zimbabwe": "233",
    "Gabon": "236",
    "Gambia": "237",
    "Ghana": "238",
    "Mauritania": "239",
    "Cabo Verde": "242",
    "Kenya": "243",
    "Comoros": "244",
    "Congo (Republic of)": "245",
    "Congo (Democratic Republic)": "246",
    "Liberia": "247",
    "Libya": "248",
    "Madagascar": "249",
    "Mali": "251",
    "Morocco": "252",
    "Mauritius": "253",
    "Mozambique": "254",
    "Niger": "255",
    "Malawi": "256",
    "Zambia": "257",
    "Burkina Faso": "258",
    "Guinea-Bissau": "259",
    "Guinea": "261",
    "Cameroon": "262",
    "South Africa": "263",
    "Rwanda": "265",
    "Namibia": "267",
    "São Tomé and Príncipe": "268",
    "Senegal": "269",
    "Seychelles": "271",
    "Sierra Leone": "272",
    "Somalia": "273",
    "Equatorial Guinea": "274",
    "Sudan (before split)": "276",
    "Sudan": "277",
    "South Sudan": "278",
    "Eswatini": "281",
    "Tanzania": "282",
    "Togo": "283",
    "Chad": "284",
    "Tunisia": "285",
    "Uganda": "286",
    "Egypt": "287",
    "Central African Republic": "289",
    "Burundi": "291",
    "British Dependent Territories in Africa": "295",
    "Other Africa": "299",
    "Antigua and Barbuda": "320",
    "Barbados": "322",
    "Argentina": "323",
    "Bahamas": "324",
    "Bolivia": "326",
    "Brazil": "327",
    "Guyana": "328",
    "Belize": "330",
    "Chile": "332",
    "Dominica": "333",
    "Costa Rica": "334",
    "Dominican Republic": "335",
    "Ecuador": "336",
    "El Salvador": "337",
    "Grenada": "340",
    "Guatemala": "345",
    "Haiti": "346",
    "Honduras": "347",
    "Canada": "348",
    "Colombia": "349",
    "Cuba": "351",
    "Mexico": "353",
    "Nicaragua": "354",
    "Jamaica": "355",
    "Panama": "357",
    "Paraguay": "359",
    "Peru": "361",
    "Suriname": "364",
    "Uruguay": "365",
    "St. Lucia": "366",
    "Venezuela": "367",
    "United States": "368",
    "St. Vincent and the Grenadines": "369",
    "St. Kitts and Nevis": "370",
    "Trinidad and Tobago": "371",
    "British Dependent Territories in America": "395",
    "Other America": "399",
    "Hong Kong": "411",
    "Macau": "412",
    "Yemen": "421",
    "Armenia": "422",
    "Afghanistan": "423",
    "Bahrain": "424",
    "Azerbaijan": "425",
    "Bhutan": "426",
    "Myanmar": "427",
    "Brunei": "429",
    "Georgia": "430",
    "Sri Lanka": "431",
    "Vietnam": "432",
    "North Korea": "434",
    "India": "436",
    "Indonesia": "437",
    "Iraq": "438",
    "Iran": "439",
    "Israel": "441",
    "Japan": "442",
    "Kazakhstan": "444",
    "Jordan": "445",
    "Cambodia": "446",
    "Qatar": "447",
    "Kuwait": "448",
    "Laos": "449",
    "Kyrgyzstan": "450",
    "Lebanon": "451",
    "Maldives": "454",
    "Oman": "456",
    "Mongolia": "457",
    "Nepal": "458",
    "Palestinian Territories": "459",
    "Bangladesh": "460",
    "Pakistan": "461",
    "Philippines": "462",
    "Taiwan": "465",
    "South Korea": "467",
    "United Arab Emirates": "469",
    "Tajikistan": "470",
    "Turkmenistan": "471",
    "Saudi Arabia": "472",
    "Singapore": "474",
    "Syria": "475",
    "Thailand": "476",
    "Uzbekistan": "477",
    "China": "479",
    "Malaysia": "482",
    "Other Asia": "499",
    "Australia": "523",
    "Solomon Islands": "524",
    "Northern Mariana Islands": "525",
    "Fiji": "526",
    "Kiribati": "530",
    "Nauru": "531",
    "Vanuatu": "532",
    "New Zealand": "536",
    "Palau": "537",
    "Papua New Guinea": "538",
    "Tuvalu": "540",
    "Tonga": "541",
    "Samoa": "543",
    "Marshall Islands": "544",
    "Micronesia": "545",
    "British Dependent Territories in Oceania": "595",
    "Other Oceania": "599",
    "Unknown Foreign": "996",
    "Stateless": "997",
    "Unclarified": "998",
    "Not Specified": "999"
},
    
   
   
}

def map_value_to_died(field_name, value):
    """Map a value from ERPNext to its DIED table equivalent."""
    if field_name not in DIED_MAPPINGS:
        frappe.log_error(f"No DIED mapping defined for field: {field_name}", "DATEV Export Error")
        return ""
    
    # Get the mapping dictionary for this field
    mapping = DIED_MAPPINGS[field_name]
    
    # Try to get the mapped value
    if value and isinstance(value, str):
        result = mapping.get(value, "")
        
        # If no mapping found, log an error and use default
        if not result:
            frappe.log_error(
                f"Value '{value}' for field '{field_name}' has no DIED mapping", 
                "DATEV Export Error"
            )
            result = mapping.get('', "")  # Get default value
    else:
        # Use default value for empty inputs
        result = mapping.get('', "")
    
    return result